
import:
  - mdolab/.github:travis/jobs-env.yml
  - mdolab/.github:travis/before-install.yml
  - mdolab/.github:travis/script.yml

env:
  global:
    - DOCKER_REPO=public

install:
  - docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR && pip install .[testing] "

script:
  - |
    if [[ "$TEST_TYPE" == "docker" ]]; then
    # run tests
      docker exec -it app /bin/bash -c ". $BASHRC && cd $DOCKER_WORKING_DIR/tests && testflo . -v -n 1"
    fi

after_script:
  - docker rm -f app
